### ISSUE TITLE
Appreciation

### ISSUE THREAD

**Issue by KuraiAndras** [davidikin45/EntityFrameworkCore.LocalStorage#1]
Not an actual issue, just wanted you to know, that I have just spend half of my weekend trying to come up with this exact library, then when it didn't work, started researching this topic more, and then found your library, and it works like a charm.

Thank you

**Comment by davidikin45** [comment]
Glad it works, need to disable linking for production build

**Comment by KuraiAndras** [comment]
Yes i have noticed that. I have tried to use the linker xml to not strip the ef assemblies but had little success. Did you have any luck configuring that?

**Comment by davidikin45** [comment]
Yeah I tried doing the same with no luck, I think it's a limitation of EF Core atm as even when I use EF Core + InMemory it has linking problems also

**Comment by davidikin45** [comment]
I made some changes and linking now works with:

<PropertyGroup>
  <BlazorWebAssemblyEnableLinking>true</BlazorWebAssemblyEnableLinking>
</PropertyGroup>

<ItemGroup>
    <BlazorLinkerDescriptor Include="LinkerConfig.xml" />
</ItemGroup>

<?xml version="1.0" encoding="UTF-8" ?>

<linker>
  <assembly fullname="System.Core" /> 
</linker>
